### ISSUE TITLE
rkmppenc_*_Ubuntu22.04_arm64.debのインストールエラー

### ISSUE THREAD

**Issue by masnagam** [rigaya/rkmppenc#5]
ubuntu 22.04には以下が存在しません

* libssl1.1
* libvpx6

https://github.com/rigaya/rkmppenc/blob/9983a48f2846946f298a57ed09da589aa625d65c/build_deb.sh#L24

未確認ですが，以下に置き換えることでエラーは解消すると思われます．

* libssl3
  * https://packages.ubuntu.com/ja/jammy/libssl3
* libvpx7
  * https://packages.ubuntu.com/ja/jammy/libvpx7

**Comment by rigaya** [comment]
ご指摘ありがとうございます。Ubuntu 22.04では検証できておりませんでした。

次回更新時に反映させていただきます。

**Comment by rigaya** [comment]
遅くなりましたが、ご指摘いただいた依存パッケージの変更を[rkmppenc 0.04](https://github.com/rigaya/rkmppenc/releases/tag/0.04)で反映し、またUbuntu 22.04環境でインストール可能となったことを確認いたしました。

ご連絡いただき、ありがとうございました。
