### ISSUE TITLE
Inquiry on install instructions OpenCL modules

### ISSUE THREAD

**Issue by bagong** [rigaya/rkmppenc#6]
Hi,

in your OpenCL modules install instructions for linux you state "Required modules will differ depending on your SoC". If I understand correctly that means I have to identify the correct deb-package in https://github.com/tsukumijima/libmali-rockchip/releases/tag/v1.9-1-53c16ef and can't just copy your example code. Unfortunately I don't understand the abbreviations in the filenames of libmali. I have an Orange Pi 5 plus and know it has a mali g610. But as to g6p0 vs g13p0, and the various options like X11, X11-gbm, wayland etc, I have no idea what to chose. I am using Joshua Riek's Ubuntu 22.04 "preinstalled Desktop" image using Gnome, with all the latest drivers. A package "libmali-g610-x11", maintained by lijianfeng1994, version 1.0.5-1 is installed. `rkmppenc --check-mppinfo` produces the expected results. On that base, could you tell me which of the libmali-valhall-g610 files to select and install? Thanks, and I hope this enquiry is not totally misplaced...

**Comment by rigaya** [comment]
g13p0 and g6p0 seems to be driver version, so the latest g13p0 will be better. (actually g13p0 was faster than g6p0)

I'm not sure of X11, wayland, gbm, but for me the one written in the install instruction worked fine with Rock5B, RK3588, Offical Ubuntu 20.04, but you can try the one which seems to be all is included (x11-wayland-gbm).

**Comment by bagong** [comment]
Okay thanks, I'll try all included 😉

**Comment by tsukumijima** [comment]
For the RK3588/RK3588S device, `libmali-valhall-g610-g13p0-wayland-gbm_1.9-1_arm64.deb` is probably the desirable choice.
I'm not quite clear about what the variants like g13p0 or -wayland indicate, but to be honest, it seems that the part up to `libmali-valhall-g610-g13p0` is important, and the suffix beyond that doesn't seem to alter the operation.
I haven't tested it in various environments, but at least on the NanoPi R6S, it worked with this.

**Comment by bagong** [comment]
Unfortunately I haven't tried anything yet. I am running an Opi5 plus with Josh Riek's Ubuntu 22.04, and it runs surprisingly well. However they use the "panfork" drivers. My impression is that they would conflict with each other? Sorry if this sounds stupid...

**Comment by rigaya** [comment]
This module is driver to run OpenCL on GPUs, if OpenCL works fine with your "panfork" drivers (I don't know the details of it), it's fine, you need not to install the module here.

You can check whether OpenCL works by ```clinfo``` command, or ```rkmppenc --check-clinfo```. They will show various information of the GPU if OpenCL can be used, and will say GPU not found if not.

**Comment by rigaya** [comment]
You also might try images [here](https://joshua-riek.github.io/ubuntu-rockchip-download/boards/rock-5b.html), which already includes OpenCL modules.

I'll close the issue as the topic has been answered.
