### ISSUE TITLE
rk3568

### ISSUE THREAD

**Issue by fanivan** [rigaya/rkmppenc#8]
how to complie rk3568

**Comment by rigaya** [comment]
Although I haven’t tested on rk3568, I think the build procedures should be the same as rk3588 shown in instructions.

Also I think the current release package should work fine.

**Comment by rigaya** [comment]
If you've having error in rk3568, [rkmppenc 0.08](https://github.com/rigaya/rkmppenc/releases/tag/0.08) might work as it fixes segmentation fault error on soc besides rk3588.

**Comment by rigaya** [comment]
I'll close the issue as the question has been answered.
